Create test Tekton task

diff --git a/.tekton/tasks.yml b/.tekton/tasks.yml
--- a/.tekton/tasks.yml
+++ b/.tekton/tasks.yml
@@ -33,3 +33,28 @@ spec:
           # Delete files and directories starting with .. plus any other character
           rm -rf "${WORKSPACE_SOURCE_PATH}"/..?*
         fi
+---
+apiVersion: tekton.dev/v1beta1
+kind: Task
+metadata:
+  name: nose
+spec:
+  workspaces:
+    - name: source  # Define the workspace where the code is located
+
+  params:
+    - name: args  # Arguments to pass to nosetests
+      description: Arguments to pass to nose
+      type: string
+      default: "-v"  # Default argument for verbose output
+
+  steps:
+    - name: nosetests  # Step to run tests using nose
+      image: python:3.9-slim  # Use a Python 3.9 image
+      workingDir: $(workspaces.source.path)  # Set working directory to the workspace
+      script: |
+        #!/bin/bash
+        set -e  # Exit immediately if any command fails
+        python -m pip install --upgrade pip wheel  # Upgrade pip and install wheel
+        pip install -r requirements.txt  # Install dependencies
+        nosetests $(params.args)  # Run nosetests with provided arguments
